   ceph mgr module disable ansible
   ceph mgr module disable deepsea
   ceph mgr module disable influx
   ceph mgr module disable insights
   ceph mgr module disable localpool
   ceph mgr module disable pg_autoscaler
   ceph mgr module disable prometheus
   ceph mgr module disable selftest
   ceph mgr module disable telegraf
   ceph mgr module disable telemetry
   ceph mgr module disable test_orchestrator
   ceph mgr module disable zabbix
